apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  # strategy:
   #  type : RollingUpdate  #TBH RollingUpdate is a default value for the strategy so there's no point to define it, but I put it as a comment due to the task
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2 # ofc it can be parametrized with values like this {{ .Values.imageRepo }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/app/config.json"
          subPath: "config.json"
          name: config-volume
        - mountPath: "/etc/secrets"
          readOnly: true
          name: secret-volume
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Chart.Name }}-configmap
      - name: secret-volume
        secret:
          secretName: {{ .Chart.Name }}