apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.ingressClass }}
  rules:
  - host:  {{ .Values.ingress.host }}
    http:
      paths:
      {{- range .Values.ingress.appPaths }}
      - pathType: Prefix
        path: {{ .path }}
        backend:
          service:
            name: {{ $.Chart.Name }}
            port:
              number: {{ .port }}
      {{- end }}