apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
    - port: {{ .port}}
      targetPort: {{ .targetPort }}
      protocol: TCP
      name: http
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-replicaset