deployment:
  replicas: 2

replicaSet:
  replicas: 2

  resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        memory: 128Mi

  commandArgs: ""

  livenessProbe:
    httpGet:
      path: /healthcheck
      port: 8080
    periodSeconds: 10
    initialDelaySeconds: 3
  readinessProbe:
    httpGet:
      path: /readinesscheck
      port: 8080
    periodSeconds: 10
    initialDelaySeconds: 3

service:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
    - port: 8081
      targetPort: 8081
    - port: 8082
      targetPort: 8082

ingress:
  appPaths:
    - path: "/api"
      port: 8080
    - path: "/logs"
      port: 8082
    - path: "/soap"
      port: 8083